WIFI_ATBM6062S_CUSTOM_SITE = $(BR2_EXTERNAL_THINGINO_PATH)/package/wifi-atbm6062s-custom/atbm-wifi-local
WIFI_ATBM6062S_CUSTOM_SITE_METHOD = local

WIFI_ATBM6062S_CUSTOM_LICENSE = GPL-2.0

WIFI_ATBM6062S_CUSTOM_MODULE_SUBDIRS = hal_apollo

WIFI_ATBM6062S_CUSTOM_MODULE_MAKE_OPTS = \
	KDIR=$(LINUX_DIR)

define WIFI_ATBM6062S_CUSTOM_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_WLAN)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WIRELESS_EXT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_CORE)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PROC)
	$(call KCONFIG_ENABLE_OPT,CONFIG_WEXT_PRIV)
	# Use kernel's CFG80211 instead of driver's custom one
	$(call KCONFIG_ENABLE_OPT,CONFIG_CFG80211)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,y)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_MINSTREL_HT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_MAC80211_RC_DEFAULT_MINSTREL)
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211_RC_DEFAULT,"minstrel_ht")
endef

LINUX_CONFIG_LOCALVERSION = $(shell awk -F "=" '/^CONFIG_LOCALVERSION=/ {print $$2}' $(BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE))

define WIFI_ATBM6062S_CUSTOM_INSTALL_CONFIGS
	$(INSTALL) -m 0755 -d $(TARGET_DIR)/lib/modules/3.10.14$(LINUX_CONFIG_LOCALVERSION)
	touch $(TARGET_DIR)/lib/modules/3.10.14$(LINUX_CONFIG_LOCALVERSION)/modules.builtin.modinfo

	$(INSTALL) -m 0755 -d $(TARGET_DIR)/usr/share/wifi
	$(INSTALL) -m 0644 -t $(TARGET_DIR)/usr/share/wifi \
		$(WIFI_ATBM_WIFI_PKGDIR)/files/*.txt

	$(INSTALL) -D -m 0644 $(@D)/firmware/cronus_SDIO_NoBLE_SDIO_svn19514_24M_wifi6phy_DCDC.bin \
		$(TARGET_DIR)/lib/firmware/atbm6062s_fw.bin
endef

WIFI_ATBM6062S_CUSTOM_POST_INSTALL_TARGET_HOOKS += WIFI_ATBM6062S_CUSTOM_INSTALL_CONFIGS

define WIFI_ATBM6062S_CUSTOM_COPY_CONFIG
	$(INSTALL) -D -m 0644 $(@D)/configs/atbm6062s.config \
		$(@D)/.config
endef

WIFI_ATBM6062S_CUSTOM_PRE_CONFIGURE_HOOKS += WIFI_ATBM6062S_CUSTOM_COPY_CONFIG

$(eval $(kernel-module))
$(eval $(generic-package))
