#!/bin/sh

on_exit() {
  mountpoint -q /proc && umount /proc
  exec /sbin/init "$@"
}

trap 'on_exit "$@"' EXIT

mount -t proc proc /proc || exit 1
grep -q overlay /proc/filesystems || exit 1

if ! grep -q 'root=.*nfs\|mmcblk\|ram' /proc/cmdline; then
  if grep -q ubifs /proc/cmdline; then
    mount -t ubifs ubi0:rootfs_data /overlay
  else
    mtdblkdev=$(awk -F ':' '/rootfs_data/ {print $1}' /proc/mtd | sed 's/mtd/mtdblock/')
    mtdchrdev=$(grep 'rootfs_data' /proc/mtd | cut -d: -f1)

    mount -t jffs2 /dev/${mtdblkdev} /overlay

    if [ $? -ne 0 ] || dmesg | grep -q "jffs2.*: Magic bitmask.*not found"; then
      echo "Init: Invalid JFFS2 blocks detected. Formatting required."
      umount /overlay
      flash_eraseall -j /dev/${mtdchrdev}
      mount -t jffs2 /dev/${mtdblkdev} /overlay || mount -t tmpfs tmpfs /overlay || exit 1

      if ! grep -q ${mtdblkdev} /proc/mounts; then
        echo "Init: ERROR: Failed to mount Overlay!"
        exit 1
      fi
    fi
  fi

  mkdir -p /overlay/upper /overlay/work /overlay/root

  if grep -q overlay /proc/filesystems; then
    mount -t overlay overlay -o lowerdir=/,upperdir=/overlay/root,workdir=/overlay/work /mnt || {
      umount /overlay
      exit 1
    }
  else
    echo "Init: ERROR: Overlay filesystem not supported!"
    umount /overlay
    exit 1
  fi

  pivot_root /mnt /mnt/rom
  mount -o noatime,move /rom/proc /proc
  mount -o noatime,move /rom/dev /dev
  mount -o noatime,move /rom/overlay /overlay
fi